on:
    push:
      branches:
        - dify/develop
      paths:
        - .github/workflows/deploy-api.yml
        - 'api/**'

name: Build and Deploy `Dify API` to dev server

jobs: 
    build-push-notify:
      name: Build, deploy, and notify
      uses: bahasa-ai/workflows/.github/workflows/deploy-ssh-notify-lark.yml@main
      with:
        package-name: dify-api
        deploy-directory: /home/labahasa/repos/dify
        working-directory: api
        version-script: echo "1.0.0"
        deploy-script: | 
          pm2 restart ecosystem.config.js
        target-hostname: github:dev-lintasarta-bjb@warpgate.bahasalab.com
        group-id: NONE
      secrets:
        lark-app-id: ${{ secrets.LARK_APP_ID }}
        lark-app-secret: ${{ secrets.LARK_APP_SECRET }}
        ssh-keys: |
          id_ed25519: ${{ toJson(secrets.AWS_DEV_SSH_KEY) }}